language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

before_install:
 - chmod +x gradlew

script:
- ./gradlew assembleDebug

after_script:
- ./gradlew testReleaseUnitTest

branches:
  only:
    - master
    - development

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle