language: java

jdk:
  - oraclejdk7

addons:
  apt:
    packages:
      - oracle-java7-installer # Updates JDK 7 to the latest available.

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
      - oracle-java7-installer


branches:
  only:
    - master
    - development